spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudproject?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: ryy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 5
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-timeMillis: 300000
    validation-query: select 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  aop:
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1
        min-idle: 5
  cloud:
    compatibility-verifier:
      enabled: false
#mybatis-plus插件配置
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ruan.yuanyuan.entity
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    call-setters-on-nulls: true #null忽略
  global-config:
    db-config:
      id-type: uuid
      update-strategy: not_null #可以修改某值为空
logging:
  level:
    com.ruan.yuanyuan.dao: DEBUG
